### ISSUE TITLE
Error in Radarr - Test Works / Sonarr works fine

### ISSUE THREAD

**Issue by deckgamez** [NiNiyas/Bettarr-Notifications#2]
Hello, I'm getting this error inside Radarr. 

2022-07-22 11:29:59.7|Error|main.py|Traceback (most recent call last):
2022-07-22 11:29:59.7|Error|main.py|  File "/home/(removed)/.local/lib/python3.9/site-packages/requests/models.py", line 971, in json
2022-07-22 11:29:59.7|Error|main.py|    return complexjson.loads(self.text, **kwargs)
2022-07-22 11:29:59.7|Error|main.py|  File "/home/(removed)/.local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
2022-07-22 11:29:59.7|Error|main.py|    return _default_decoder.decode(s)
2022-07-22 11:29:59.7|Error|main.py|  File "/home/(removed)/.local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
2022-07-22 11:29:59.7|Error|main.py|    obj, end = self.raw_decode(s)
2022-07-22 11:29:59.7|Error|main.py|  File "/home/(removed)/.local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
2022-07-22 11:29:59.7|Error|main.py|    return self.scan_once(s, idx=_w(s, idx).end())
2022-07-22 11:29:59.7|Error|main.py|simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-07-22 11:29:59.7|Error|main.py|During handling of the above exception, another exception occurred:
2022-07-22 11:29:59.7|Error|main.py|Traceback (most recent call last):
2022-07-22 11:29:59.7|Error|main.py|  File "/home/(removed)/Bettarr-Notifications/src/main.py", line 279, in <module>
2022-07-22 11:29:59.7|Error|main.py|    radarr_send()
2022-07-22 11:29:59.7|Error|main.py|  File "/home/(removed)/Bettarr-Notifications/src/main.py", line 161, in radarr_send
2022-07-22 11:29:59.7|Error|main.py|    telegram_radarr.radarr_import()
2022-07-22 11:29:59.7|Error|main.py|  File "/home/(removed)/Bettarr-Notifications/src/notifiers/Telegram/telegram_radarr.py", line 116, in radarr_import
2022-07-22 11:29:59.7|Error|main.py|    radarr = radarr.json()
2022-07-22 11:29:59.7|Error|main.py|  File "/home/(removed)/.local/lib/python3.9/site-packages/requests/models.py", line 975, in json
2022-07-22 11:29:59.7|Error|main.py|    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2022-07-22 11:29:59.7|Error|main.py|requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

not sure how to fix. Thanks

**Comment by NiNiyas** [comment]
Hi! I am very sorry for the late reply. The traceback indicates that the script has trouble connecting to radarr api. Is it working for the grab notifications? Can you also post the contents from log file? It should be in the logs directory.

**Comment by deckgamez** [comment]
No worries, I understand, life comes first. Thanks for the reply.

I'll check the API, but it does work for the TEST notification. Not for grabs. I'll get the logs shortly.

**Comment by NiNiyas** [comment]
Closing stale issue. Feel free to reopen.
